### ISSUE TITLE
Errors in Podfile

### ISSUE THREAD

**Issue by djfitz** [ABTSoftware/SciChart.iOS.Examples#1]
The following Podfile has errors:

https://github.com/ABTSoftware/SciChart.iOS.Examples/tree/master/v2.x/Examples/Podfile

1. Contains incorrect quote characters
"[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice."

2. Podfile specifies a version of the SciChart pod that doesn't exist

Version 2.0.0.1301 doesn't seem to exist. Maybe change the Podfile to not specify a version number?

**Comment by andyb1979** [comment]
Hi doug, 

My bad. We realised today the PodFile wasn't pulling latest version, so made a change to include the version number in the PodFile. Then the build broke which published the Examples source but not the Cocoapod hence the version mismatch. 

We've since made changes to publish and check Cocoapod _before_ publishing the examples source and to ensure the version numbers are in sync. Part of this process another team member broke the build which lost us a few hours investigating the deployment of above examples. 

Anyway, it's fixed now :) Build is green! Pull the latest and let me know. 

Finally, smart quotes issue is just a warning, but I'll take a look at this now...

Best regards, 
Andrew 
[SciChart Team]

**Comment by djfitz** [comment]
Thanks, I hear you about release versioning; such a drag. But will try the latest.

FWIW, I think to get latest podspec version, use 'pod update'. To use same version of pod in generated podfile.lock, use 'pod install'. 'pod update' should always get the latest version. 'pod install' guarantees to use the last version generated by 'pod update'.

**Comment by andyb1979** [comment]
You're right. You need Pod Update too. But revision 2.0.0.1304 plain didn't exist in the PodSpecs repository https://github.com/ABTSoftware/PodSpecs.git

Our build is green but when I try to compile locally, it's still showing a different error. Still investigating ...

**Comment by djfitz** [comment]
Don't know if this is a related issue, but I'm having a hard time building this demo application.

See attached error log.

[Build SciChartDemo_2017-04-19T14-01-49.txt](https://github.com/ABTSoftware/SciChart.iOS.Examples/files/938415/Build.SciChartDemo_2017-04-19T14-01-49.txt)

**Comment by andyb1979** [comment]
That;s not it .. Im seeing info.plist missing (but it is on disk). I suspect I have some old builds knocking around on disk so I decided to do an XCode upgrade to 8.3.1 (same as the build server) to see if issues persist. 

Annoyingly our build is GREEN which doesn't help us identify issues. 

Rest assured its very high priority for us to have this repo as Clone-and-go so while it's late here we will be working to sort it out as soon as poss.

**Comment by andyb1979** [comment]
OK after much headbanging, the team has resolved this. 

![SciChart.iOS.Examples Build Success](https://www.scichart.com/wp-content/uploads/2017/04/scichart-build-success.png)

We had multiple issues, including one in the Cocoapod file where it did not fetch or build the pods for all architectures, only the active architecture. 

Can you do me a favour:

> git clean
> git reset --HARD
> git pull

to update your repo, followed by

> cd v2.x/Examples
> pod install
> pod update
> cd ..
> cd Showcase
> pod install
> pod update

To install the pods

Now 

> cd ..
> open . 

and open the Examples/SciChart.iOS.Examples.xcworkspace generated by the pod install. You may need to Clean then Build in XCode with Scheme = SciChartDemo, Target = iPhone <simulator> or device

Let me know what happens.

**Comment by djfitz** [comment]
OK, I did a clean clone of this repo and the examples and showcase are now building. Thanks so much for getting this working! I'm checking out the relevant features now.

**Comment by andyb1979** [comment]
No problem ... I'm embarrassed it wasn't working in the first place. Some problems in our build server setup. It was showing green when in fact it was red. This has now been sorted, we should only be pushing working code from now on ! 👍 :)
