### ISSUE TITLE
Cannot build the examples after checkout

### ISSUE THREAD

**Issue by iGranDav** [ABTSoftware/SciChart.iOS.Examples#11]
hi 👋  I cannot build the project after checkout the `SciChart_v4_Release` branch

```
$ pod --version
1.9.3
```

<img width="1488" alt="Capture d’écran 2020-09-17 à 14 00 23" src="https://user-images.githubusercontent.com/75418/93467589-2b43f400-f8ee-11ea-8b3a-1f8aac97b355.png">

Trying to build on device or even on the mac does the same thing.

**Comment by andriypohorilko** [comment]
Hi, there.

Please try to update the CocoaPods to 1.10.0.rc.1, this should fix the problem.
https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.rc.1

Please let us know if it works for you.

**Comment by kutakmir** [comment]
Hi @andriypohorilko I am getting the same error with pod --version:
```
1.10.1
```

Does this framework work under that version or do I have to downgrade?

**Comment by nrudnyk** [comment]
hi @kutakmir, there's no needs in CocoaPods anymore. We've replaced it with SwiftPM, so you should just clone and be good to go.

**Comment by nrudnyk** [comment]
since this is a duplicate of #14 I'm closing
