### ISSUE TITLE
Error in AudioRecorder.m

### ISSUE THREAD

**Issue by slmille4** [ABTSoftware/SciChart.iOS.Examples#13]
The code
    for (unsigned int i = 0; i < numSamples; i++) {
        audioBufferComplex[i].real = dataFloat[i];
        audioBufferComplex[i].imag = 0.0f;
    }
    vDSP_ctoz(audioBufferComplex, 2, &tempSplitComplex, 1, numSamples);

should just be
   vDSP_ctoz((DSPComplex*)dataFloat, 2, &tempSplitComplex, 1, numSamples/2);

This will produce an even array and odd array as is needed for the real-to-complex FFT

**Comment by nrudnyk** [comment]
feel free to create a pull request with changes and we can review that later on.
