### ISSUE TITLE
SciChart.iOS.Examples-SciChart_v4_Release -> SciChartDemo.Mac -> cannot compile the sample after downloading

### ISSUE THREAD

**Issue by kutakmir** [ABTSoftware/SciChart.iOS.Examples#14]
## Repro steps:
1. Download repo SciChart.iOS.Examples-SciChart_v4_Release
2. Open SciChartDemo.Mac in Xcode
3. Wait for it to resolve packages
4. oops, now you see an error

## The error

<img width="1512" alt="Screenshot 2021-07-11 at 22 35 56" src="https://user-images.githubusercontent.com/1864402/125209342-5e4dde80-e298-11eb-9a8a-b9d70d6fe116.png">

**Comment by nrudnyk** [comment]
hi @kutakmir . That's now fixed, so you should be just good to go. In case you have any issues - try resetting Swift Package Caches via `File > Swift Packages > Reset Package Caches`

**Comment by kutakmir** [comment]
@nrudnyk yes, now we have another issue:

<img width="1751" alt="Screenshot 2021-07-14 at 22 50 54" src="https://user-images.githubusercontent.com/1864402/125691096-ddf6873d-56c4-4235-94c6-99e7d42bb917.png">

MacOS
11.4 (20F71)

Xcode
Version 12.4 (12D4e)

**Comment by nrudnyk** [comment]
that's an issue only with Xcode 12.4. 12.3 and 12.5 has this fixed. So you should either update or downgrade. 
if you can't upgrade - you can workaround this by passing parameter with default value, but I'd rather update

**Comment by kutakmir** [comment]
@nrudnyk it works now, thank you!
