### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by sunzeboy** [ABTSoftware/SciChart.iOS.Examples#5]
The following is my operation in the terminal:

- ➜  SciChartShowcase pod install
- Analyzing dependencies
- Downloading dependencies
- Installing SciChart (2.2.2.2291)
- 
- [!] Error installing SciChart
- [!] /usr/bin/curl -f -L -o /var/folders/4b/xxk277rx55lds_k_snghy8gr0000gn/T/d20190103-826-kp7ifc/file.zip https://github.com/ABTSoftware/PodSpecs/releases/download/v2.2.2.2291/SciChart_iOS_Framework.zip --create-dirs --netrc-optional --retry 2
- 
-   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
-                                  Dload  Upload   Total   Spent    Left  Speed
- 100   616    0   616    0     0    903      0 --:--:-- --:--:-- --:--:--   904
-   1 11.6M    1  203k    0     0    256      0 13:15:17  0:13:33 13:01:44     0
- curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by andyb1979** [comment]
Hello, 

the file exists on the PodSpecs directory, and our build server is green (which uses our Cocoapod to compile the examples). You can try googling the error message and/or looking at your local environment (Cocoapod version, Home-brew version etc...)
