### ISSUE TITLE
Audio Analyzer Showcase iOS Example Crash

### ISSUE THREAD

**Issue by antiero** [ABTSoftware/SciChart.iOS.Examples#6]
Using Xcode 10.1, in Simulator and on iPhone 8 Device running iOS 12.1.2, I am seeing a crash moments after the Audio Analyzer example launches.

To repro:

cd. Showcase/SciChartShowcase
pod install
open .
Double-click the SciChart.iOS.Showcase.xcworkspace
Build and Run the Launch SciChartShowcaseDemo.
Click 'skip' then choose the Audio Analyzer example.

Result: Graphs are displayed momentarily, but then the App Crashes:

2019-01-28 19:14:53.564517+0000 SciChartShowcaseDemo[17227:365842] 317:  ca_debug_string: inPropertyData == NULL
SciChartShowcaseDemo(17227,0x117cc65c0) malloc: *** error for object 0x124fe9000: pointer being freed was not allocated
SciChartShowcaseDemo(17227,0x117cc65c0) malloc: *** set a breakpoint in malloc_error_break to debug
(lldb)

**Comment by nrudnyk** [comment]
SciChartShowcase is obsoleted for quite a long time now, audio analyser can be found directly in examples app.
